name: Build & Test

on: [push]

jobs:
  collect_metrics:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: metrics
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=\"$HOME/.local/bin:$PATH\"" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          poetry install
      - name: Retrieve the credentials and decode to a file
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          echo $CREDENTIALS_JSON | base64 --decode > datagov_metrics/credentials.json
      - name: Run Python script
        run: |
          poetry run python datagov_metrics/poc.py

  build_site:
    runs-on: ubuntu-latest
    needs: collect_metrics
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true #runs `bundle install`
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install NPM dependencies
        shell: bash
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Woke scan
        uses: get-woke/woke-action@v0
        with:
          # Cause the check to fail on any broken rules
          fail-on-error: false
